// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/phongnd2802/go-ecommerce/internal/controllers"
	"github.com/phongnd2802/go-ecommerce/internal/database/sqlc"
	"github.com/phongnd2802/go-ecommerce/internal/repositories"
	"github.com/phongnd2802/go-ecommerce/internal/services"
)

// Injectors from wire.access.go:

func InitAccessRouterHandler(db *sql.DB) (*controllers.AccessController, error) {
	store := database.NewStore(db)
	iShopRepository := repositories.NewShopRepository(store)
	iAccessService := services.NewAccessService(iShopRepository)
	accessController := controllers.NewAccessController(iAccessService)
	return accessController, nil
}
