ALTER TABLE clothes MODIFY COLUMN size VARCHAR(255) NOT NULL;
ALTER TABLE clothes MODIFY COLUMN material VARCHAR(255) NOT NULL;

ALTER TABLE electronics MODIFY COLUMN model VARCHAR(255) NOT NULL;
ALTER TABLE electronics MODIFY COLUMN color VARCHAR(255) NOT NULL;

ALTER TABLE furnitures MODIFY COLUMN size VARCHAR(255) NOT NULL;
ALTER TABLE furnitures MODIFY COLUMN material VARCHAR(255) NOT NULL;