server:
  host: 127.0.0.1
  port: 8000
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 12345
  dbName: GoDEV
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: "./storages/logs/dev.log"
  max_size: 500
  max_backups: 3
  max_age: 30
  compress: true