// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Role struct {
	ID              int32
	RoleName        string
	RoleDescription sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Shop struct {
	ID        string
	ShopName  string
	Email     string
	Password  string
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ShopRole struct {
	ShopID    sql.NullString
	RoleID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
