// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type DiscountsDiscountAppliesTo string

const (
	DiscountsDiscountAppliesToAll      DiscountsDiscountAppliesTo = "all"
	DiscountsDiscountAppliesToSpecific DiscountsDiscountAppliesTo = "specific"
)

func (e *DiscountsDiscountAppliesTo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountsDiscountAppliesTo(s)
	case string:
		*e = DiscountsDiscountAppliesTo(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountsDiscountAppliesTo: %T", src)
	}
	return nil
}

type NullDiscountsDiscountAppliesTo struct {
	DiscountsDiscountAppliesTo DiscountsDiscountAppliesTo
	Valid                      bool // Valid is true if DiscountsDiscountAppliesTo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountsDiscountAppliesTo) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountsDiscountAppliesTo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountsDiscountAppliesTo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountsDiscountAppliesTo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountsDiscountAppliesTo), nil
}

type ProductsProductType string

const (
	ProductsProductTypeElectronics ProductsProductType = "Electronics"
	ProductsProductTypeClothing    ProductsProductType = "Clothing"
	ProductsProductTypeFurniture   ProductsProductType = "Furniture"
)

func (e *ProductsProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsProductType(s)
	case string:
		*e = ProductsProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsProductType: %T", src)
	}
	return nil
}

type NullProductsProductType struct {
	ProductsProductType ProductsProductType
	Valid               bool // Valid is true if ProductsProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsProductType), nil
}

type ApiKey struct {
	ID          int32
	Akey        string
	Status      sql.NullBool
	Permissions string
}

type Clothe struct {
	ID          string
	Brand       string
	ProductShop string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Size        string
	Material    string
}

type Discount struct {
	ID                     string
	DiscountName           string
	DiscountDescription    string
	DiscountType           string
	DiscountValue          int32
	DiscountCode           string
	DiscountStartDate      time.Time
	DiscountEndDate        time.Time
	DiscountMaxUses        int32
	DiscountUsesCount      int32
	DiscountMaxUsesPerUser int32
	DiscountMinOrderValue  int32
	DiscountShopID         string
	DiscountIsActive       bool
	DiscountAppliesTo      DiscountsDiscountAppliesTo
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type DiscountProductID struct {
	DiscountID string
	ProductID  string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type DiscountUsersUsed struct {
	DiscountID string
	UserID     string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Electronic struct {
	ID           string
	Manufacturer string
	ProductShop  string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Model        string
	Color        string
}

type Furniture struct {
	ID          string
	Brand       string
	ProductShop string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Size        string
	Material    string
}

type Product struct {
	ID                   string
	ProductName          string
	ProductThumb         string
	ProductDescription   sql.NullString
	ProductPrice         string
	ProductQuantity      int32
	ProductType          ProductsProductType
	ProductShop          string
	ProductAttributes    json.RawMessage
	ProductRatingaverage sql.NullString
	ProductVariations    json.RawMessage
	Isdraft              sql.NullBool
	Ispublished          sql.NullBool
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	ProductSlug          sql.NullString
}

type Role struct {
	ID              int32
	RoleName        string
	RoleDescription sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Shop struct {
	ID        string
	ShopName  string
	Email     string
	Password  string
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ShopRole struct {
	ShopID    sql.NullString
	RoleID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Token struct {
	ID               string
	PublicKey        string
	RefreshToken     string
	RefreshTokenUsed sql.NullString
	ShopID           string
}
